apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-deploy
  labels:
    app: 2048-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: 2048-app
  template:
    metadata:
      labels:
        app: 2048-app
    spec:
      containers:
        - name: eks-app
          image: youcefd/2048_game:latest
          command: ["python", "-m", "http.server", "3000"]
          ports:
            - containerPort: 3000

--- 

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-2048
  annotations:
    cert-manager.io/cluster-issuer: issuer
spec:
  ingressClassName: nginx
  rules:
  - host: 2048-app.youcefderder.co.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-2048
            port:
              number: 80

--- 

apiVersion: v1
kind: Service
metadata:
  name: service-2048
spec:
  selector:
    app: 2048-app
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 3000
  type: ClusterIp
